/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : oc_pal1.h
**     Project     : oc_pal_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : oc_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 20:43, # CodeGen: 0
**     Contents    :
**         OC_Init                - status_t OC_Init(const oc_instance_t * const instance, const oc_config_t *...
**         OC_Deinit              - status_t OC_Deinit(const oc_instance_t * const instance);
**         OC_StartChannel        - void OC_StartChannel(const oc_instance_t * const instance, const uint8_t...
**         OC_StopChannel         - void OC_StopChannel(const oc_instance_t * const instance, const uint8_t...
**         OC_SetOutputState      - status_t OC_SetOutputState(const oc_instance_t * const instance, const...
**         OC_SetOutputAction     - status_t OC_SetOutputAction(const oc_instance_t * const instance, const...
**         OC_SetCompareValue     - status_t OC_SetCompareValue(const oc_instance_t * const instance, const...
**         OC_EnableNotification  - void OC_EnableNotification(const oc_instance_t * const instance, const...
**         OC_DisableNotification - void OC_DisableNotification(const oc_instance_t * const instance, const...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file oc_pal1.h
** @version 01.00
*/
/*!
**  @addtogroup oc_pal1_module oc_pal1 module documentation
**  @{
*/
#ifndef oc_pal1_H
#define oc_pal1_H

/* MODULE oc_pal1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "oc_pal.h"
#include "Cpu.h"




/*! @brief Device instance number */
extern const oc_instance_t oc_pal1_instance;

/* Channels configuration structure for oc_pal1 output compare channels */
extern oc_output_ch_param_t oc_pal1_ChnConfig[1];

/* Channels configuration structure for oc_pal1 output compare */
/*! @brief IP specific extension configuration */
extern extension_emios_for_oc_t oc_pal1_emiosExtension;

/* Global configuration of oc_pal1 */
extern oc_config_t oc_pal1_InitConfig;

/*! @brief Callback function of channel configuration 0 */
extern void oc_pal1_channel_callBack0(oc_event_t event, void * userData);

#endif
/* ifndef oc_pal1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

