/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi2.c
**     Project     : spi_pal_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : spi_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 21:00, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file spi2.c
** @version 01.00
*/
/*!
**  @addtogroup spi2_module spi2 module documentation
**  @{
*/
#include "spi2.h"

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 */

/*! @brief SPI_PAL instance */
spi_instance_t spi2Instance = {.instType = SPI_INST_TYPE_DSPI, .instIdx = 0U};

/* SPI Master Configurations */

/* SPI Slave Configurations */
const spi_slave_t SlaveConfig0 = {.ssPolarity = SPI_ACTIVE_LOW,
                                  .frameSize = 8,
                                  .clockPhase = READ_ON_ODD_EDGE,
                                  .clockPolarity = SPI_ACTIVE_LOW,
                                  .transferType = SPI_USING_INTERRUPTS,
                                  .rxDMAChannel = 255U,
                                  .txDMAChannel = 255U,
                                  .callback = NULL,
                                  .callbackParam = NULL};

/* END spi2. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
