/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : i2s_pal2.h
**     Project     : i2s_pal_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : i2s_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-05-01, 00:34, # CodeGen: 0
**     Contents    :
**         I2S_Init                - status_t I2S_Init(const i2s_instance_t* instance, const i2s_user_config_t...
**         I2S_Deinit              - status_t I2S_Deinit(const i2s_instance_t* instance);
**         I2S_GetBaudRate         - status_t I2S_GetBaudRate(const i2s_instance_t* instance, uint32_t  *...
**         I2S_SendDataBlocking    - status_t I2S_SendDataBlocking(const i2s_instance_t* instance, const uint8_t *...
**         I2S_SendData            - status_t I2S_SendData(const i2s_instance_t* instance, const uint8_t * txBuff,...
**         I2S_Abort               - status_t I2S_Abort(const i2s_instance_t* instance);
**         I2S_GetStatus           - status_t I2S_GetStatus(const i2s_instance_t* instance, uint32_t *...
**         I2S_ReceiveDataBlocking - status_t I2S_ReceiveDataBlocking(const i2s_instance_t* instance, uint8_t *...
**         I2S_ReceiveData         - status_t I2S_ReceiveData(const i2s_instance_t* instance, uint8_t * rxBuff,...
**         I2S_SetTxBuffer         - status_t I2S_SetTxBuffer(const i2s_instance_t* instance, const uint8_t *...
**         I2S_SetRxBuffer         - status_t I2S_SetRxBuffer(const i2s_instance_t* instance, const uint8_t *...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file i2s_pal2.h
** @version 01.00
*/
/*!
**  @addtogroup i2s_pal2_module i2s_pal2 module documentation
**  @{
*/
/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced
 * These macros are used by user.
 */
#ifndef i2s_pal2_H
#define i2s_pal2_H

/* MODULE i2s_pal2. */

/* Include inherited beans */
#include "clockMan1.h"
#include "dmaController1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_I2S_PAL2 (&i2sOverSai1Instance)
extern const i2s_instance_t i2sOverSai1Instance;

/*! @brief Serial module configurations */
extern i2s_user_config_t i2s_pal2_Config0;

#endif
/* ifndef __i2s_pal2_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

