CPU:=e200z2
SYMBOLS := MPC574xG
SRC_S := ${realpath ${wildcard Project_Settings/Startup_Code/*.S}}
SRC_LD := ${realpath ${wildcard Project_Settings/Linker_Files/libs.ld}}

include $(realpath ../../include.mk)
