/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : mpu_pal1.h
**     Project     : mpu_pal_memory_protection_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : mpu_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 20:42, # CodeGen: 0
**     Contents    :
**         MPU_Init                  - status_t MPU_Init(const mpu_instance_t * const instance, uint8_t regionCnt,...
**         MPU_Deinit                - status_t MPU_Deinit(const mpu_instance_t * const instance);
**         MPU_GetDefautRegionConfig - status_t MPU_GetDefautRegionConfig(const mpu_instance_t * const instance,...
**         MPU_UpdateRegion          - status_t MPU_UpdateRegion(const mpu_instance_t * const instance, uint8_t...
**         MPU_EnableRegion          - status_t MPU_EnableRegion(const mpu_instance_t * const instance, uint8_t...
**         MPU_GetError              - bool MPU_GetError(const mpu_instance_t * const instance, uint8_t channel,...
**         MPU_UpdateRegionLock      - status_t MPU_UpdateRegionLock(const mpu_instance_t * const instance, uint8_t...
**         MPU_GetRegionLockInfo     - status_t MPU_GetRegionLockInfo(const mpu_instance_t * const instance, uint8_t...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file mpu_pal1.h
** @version 01.00
*/
/*!
**  @addtogroup mpu_pal1_module mpu_pal1 module documentation
**  @{
*/
#ifndef MPU_PAL1_H
#define MPU_PAL1_H

/* MODULE mpu_pal1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "mpu_pal.h"

/*! @brief Number of user configuration */
#define MPU_PAL_USER_CFG_CNT (1U)

/*! @brief Number of region in user configurations */
#define MPU_PAL_REGION_CFG_CNT0 (4U)

/*! @brief Structure storing PAL instance information */
extern const mpu_instance_t mpu_pal1_Instance;

/*! @brief User configuration */
extern const mpu_region_config_t mpu_pal1_RegionConfig0[MPU_PAL_REGION_CFG_CNT0];

/*! @brief Master configuration */
extern const mpu_master_access_permission_t mpu_pal1_AccessRightConfig0[FEATURE_SMPU_MASTER_COUNT];
extern const mpu_master_access_permission_t mpu_pal1_AccessRightConfig1[FEATURE_SMPU_MASTER_COUNT];
extern const mpu_master_access_permission_t mpu_pal1_AccessRightConfig2[FEATURE_SMPU_MASTER_COUNT];

/*! @brief Extension configuration */

/*! @brief Specific access rights */

#endif
/* ifndef MPU_PAL1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

