/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eMIOS1.h
**     Project     : emios_oc_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : emios_oc
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 19:57, # CodeGen: 0
**     Contents    :
**         EMIOS_DRV_OC_InitOutputCompareMode                - status_t EMIOS_DRV_OC_InitOutputCompareMode(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_SetSingleActOutputCmpMatch           - void EMIOS_DRV_OC_SetSingleActOutputCmpMatch(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_GetSingleActOutputCmpMatch           - uint32_t EMIOS_DRV_OC_GetSingleActOutputCmpMatch(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_ForceSingleActOutputCmpMatch         - void EMIOS_DRV_OC_ForceSingleActOutputCmpMatch(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_SetDoubleActOutputCmpMatch           - void EMIOS_DRV_OC_SetDoubleActOutputCmpMatch(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_GetDoubleActOutputCmpMatch           - status_t EMIOS_DRV_OC_GetDoubleActOutputCmpMatch(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_OC_ForceDoubleActOutputCmpLeadingMatch  - void EMIOS_DRV_OC_ForceDoubleActOutputCmpLeadingMatch(uint8_t emiosGroup,...
**         EMIOS_DRV_OC_ForceDoubleActOutputCmpTrailingMatch - void EMIOS_DRV_OC_ForceDoubleActOutputCmpTrailingMatch(uint8_t emiosGroup,...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eMIOS1.h
** @version 01.00
*/
/*!
**  @addtogroup eMIOS1_module eMIOS1 module documentation
**  @{
*/
#ifndef eMIOS1_H
#define eMIOS1_H
/* MODULE eMIOS1. */
#include "emios_common.h"
#include "emios_mc_driver.h"
#include "emios_oc_driver.h"
#include "eMIOS_Mc.h"
#include "Cpu.h"


/* ifndef eMIOS1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
/* eMIOS Output compare mode configuration structure for eMIOS_0 */
extern emios_oc_param_t eMIOS1_OCChnConfig0;
extern emios_oc_param_t eMIOS1_OCChnConfig1;
#endif
