/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eMIOS2.h
**     Project     : emios_ic_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : emios_ic
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 19:57, # CodeGen: 0
**     Contents    :
**         EMIOS_DRV_IC_InitInputCaptureMode - status_t EMIOS_DRV_IC_InitInputCaptureMode(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_IC_GetLastMeasurement   - status_t EMIOS_DRV_IC_GetLastMeasurement(uint8_t emiosGroup, uint8_t channel,...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eMIOS2.h
** @version 01.00
*/
/*!
**  @addtogroup eMIOS2_module eMIOS2 module documentation
**  @{
*/
#ifndef eMIOS2_H
#define eMIOS2_H

/* MODULE eMIOS2. */
#include "emios_common.h"
#include "emios_ic_driver.h"
#include "emios_mc_driver.h"
#include "eMIOS_Mc.h"
#include "Cpu.h"


/* ifndef eMIOS2_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

/* eMIOS input capture mode configuration structure for eMIOS_1 */
extern emios_input_capture_param_t eMIOS2_ICChnConfig0;
#endif
