/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : smpu1.h
**     Project     : smpu_protection_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : smpu
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 21:00, # CodeGen: 0
**     Contents    :
**         SMPU_DRV_Init                   - status_t SMPU_DRV_Init(uint32_t instance, uint8_t regionCnt, const...
**         SMPU_DRV_Deinit                 - status_t SMPU_DRV_Deinit(uint32_t instance);
**         SMPU_DRV_GetDefaultRegionConfig - smpu_user_config_t SMPU_DRV_GetDefaultRegionConfig(smpu_master_access_right_t...
**         SMPU_DRV_SetRegionConfig        - status_t SMPU_DRV_SetRegionConfig(uint32_t instance, uint8_t regionNum, const...
**         SMPU_DRV_SetRegionProcessId     - status_t SMPU_DRV_SetRegionProcessId(uint32_t instance, uint8_t regionNum,...
**         SMPU_DRV_SetRegionAddr          - status_t SMPU_DRV_SetRegionAddr(uint32_t instance, uint8_t regionNum,...
**         SMPU_DRV_EnableRegion           - status_t SMPU_DRV_EnableRegion(uint32_t instance, uint8_t regionNum, bool...
**         SMPU_DRV_SetMasterAccessRights  - status_t SMPU_DRV_SetMasterAccessRights(uint32_t instance, uint8_t regionNum,...
**         SMPU_DRV_SetRegionLockConfig    - status_t SMPU_DRV_SetRegionLockConfig(uint32_t instance, uint8_t regionNum,...
**         SMPU_DRV_GetRegionLockInfo      - smpu_region_lock_t SMPU_DRV_GetRegionLockInfo(uint32_t instance, uint8_t...
**         SMPU_DRV_GetDetailErrorInfo     - bool SMPU_DRV_GetDetailErrorInfo(uint32_t instance, uint8_t errorNum,...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file smpu1.h
** @version 01.00
*/
/*!
**  @addtogroup smpu1_module smpu1 module documentation
**  @{
*/
#ifndef SMPU1_H
#define SMPU1_H

/* MODULE smpu1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "smpu_driver.h"

/*! @brief Device instance number */
#define INST_SMPU1 (0U)

/*! @brief Number of user configuration */
#define SMPU_NUM_OF_USER_CFG (1U)

/*! @brief Number of region in user configuration */
#define SMPU_NUM_OF_REGION_CFG0 (4U)

/*! @brief User configuration */
extern const smpu_user_config_t smpu1_UserConfig0[SMPU_NUM_OF_REGION_CFG0];

/*! @brief Master access rights */
extern const smpu_master_access_right_t smpu1_AccessRightConfig0[FEATURE_SMPU_MASTER_COUNT];
extern const smpu_master_access_right_t smpu1_AccessRightConfig1[FEATURE_SMPU_MASTER_COUNT];
extern const smpu_master_access_right_t smpu1_AccessRightConfig2[FEATURE_SMPU_MASTER_COUNT];

/*! @brief Specific access rights */

#endif
/* ifndef SMPU1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
