/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eee1.c
**     Project     : eeprom_emulation_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : eee
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 19:55, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eee1.c
** @version 01.00
*/
/*!
**  @addtogroup eee1_module eee1 module documentation
**  @{
*/

/* MODULE eee1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made
 * static. The external variables will be used in other source files in
 * application code.
 */

#include "eee1.h"

/*! Global configuration of eee1 */

uint32_t table[EEE_CACHE_SIZE_IN_RAM];
eee_cache_table_t cTable = {
    .startAddress = table,
    .size = sizeof(table),
};

eee_block_config_t eee1_blockConfig0 = {
    .enabledBlock = 0x00000001U,
    .blockStartAddr = 0x00F90000U,
    .blockSize = 0x00004000U,
    .blankSpace = 0U,
    .blockSpace = C55_BLOCK_MID,
    .partSelect = 0x00000002U,
};

eee_block_config_t eee1_blockConfig1 = {
    .enabledBlock = 0x00000002U,
    .blockStartAddr = 0x00F94000U,
    .blockSize = 0x00004000U,
    .blankSpace = 0U,
    .blockSpace = C55_BLOCK_MID,
    .partSelect = 0x00000002U,
};

eee_block_config_t eee1_blockConfig2 = {
    .enabledBlock = 0x00000004U,
    .blockStartAddr = 0x00F98000U,
    .blockSize = 0x00004000U,
    .blankSpace = 0U,
    .blockSpace = C55_BLOCK_MID,
    .partSelect = 0x00000002U,
};

eee_block_config_t *fBlocksConf[3] = {
    &eee1_blockConfig0,
    &eee1_blockConfig1,
    &eee1_blockConfig2,
};

const eee_user_config_t userConf = {
    .numberOfBlock = 3U,
    .numberOfActBlock = 1U,
    .numOfByteRead = 30U,
    .numOfCycleSearch = 40U,
    .numOfRecordSearch = 2000U,
    .callback = NULL,
    .callbackParam = NULL,
    .cTable = &cTable,
    .flashBlocks = fBlocksConf,
    .schemeSelection = EEE_FIXLENGTH,
    .dataSize = 10U,
    .maxReEraseEeeBlock = 1U,
    .maxReProgram = 1U,
    .cacheEnable = true,
    .maxRecordId = 200U,
};

/* END eee1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
