/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eee1.h
**     Project     : eeprom_emulation_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : eee
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 19:55, # CodeGen: 0
**     Contents    :
**         EEE_DRV_InitEeprom         - status_t EEE_DRV_InitEeprom(const eee_uer_config_t * userConf, eee_state_t *...
**         EEE_DRV_WriteEeprom        - status_t EEE_DRV_WriteEeprom(uint16_t dataID,uint16_t dataSize,uint32_t...
**         EEE_DRV_ReadEeprom         - status_t EEE_DRV_ReadEeprom(uint16_t dataID,uint16_t dataSize,uint32_t...
**         EEE_DRV_DeleteRecord       - status_t EEE_DRV_DeleteRecord(uint16_t dataID,eee_request_type_t iReq);
**         EEE_DRV_ReportEepromStatus - status_t EEE_DRV_ReportEepromStatus(uint32_t * erasingCycles);
**         EEE_DRV_RemoveEeprom       - status_t EEE_DRV_RemoveEeprom(void);
**         EEE_DRV_MainFunction       - status_t EEE_DRV_MainFunction(void);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eee1.h
** @version 01.00
*/
/*!
**  @addtogroup eee1_module eee1 module documentation
**  @{
*/
#ifndef eee1_H
#define eee1_H

/* MODULE eee1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "eee_driver.h"

/*!  */
#define EEE_CACHE_SIZE_IN_RAM 500U

extern uint32_t table[EEE_CACHE_SIZE_IN_RAM];
extern eee_cache_table_t cTable;


/*! Global configuration of eee1 */
/*! User configuration 0 */
extern eee_block_config_t eee1_blockConfig0;
/*! User configuration 1 */
extern eee_block_config_t eee1_blockConfig1;
/*! User configuration 2 */
extern eee_block_config_t eee1_blockConfig2;

extern eee_block_config_t * fBlocksConf[3];
extern const eee_user_config_t userConf;

#endif
/* END eee1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

