/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : bctu1.c
**     Project     : bctu_trigger_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : bctu
**     Version     : Component S32_SDK_C55, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 18:38, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file bctu1.c
** @version 01.00
*/
/*!
**  @addtogroup bctu1_module bctu1 module documentation
**  @{
*/

/* MODULE bctu1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * Function is defined for usage by application code.
 */

#include "bctu1.h"

/*! bctu1 configuration structures */

const bctu_config_t bctu1_globalConfig0 = {
    .lowPowerModeEn = false,
    .globalHwTriggersEn = false,
    .globalTriggersEn = false,
    .dmaEnMask = 0U,
    .triggerIntEn = false,
    .listIntEn = true,
    .newDataIntEnMask = 2U,
};

const bctu_trig_config_t bctu1_trigConfig0 = {
    .loopEn = true,
    .adcTargetMask = 2U,
    .hwTriggersEn = false,
};

const bctu_trig_config_t bctu1_trigConfig1 = {
    .loopEn = false,
    .adcTargetMask = 2U,
    .hwTriggersEn = false,
};

/* END bctu1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
