/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : wkpu1.c
**     Project     : power_mode_switch_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : wkpu
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-05-01, 00:21, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file wkpu1.c
** @version 01.00
*/
/*!
**  @addtogroup wkpu1_module wkpu1 module documentation
**  @{
*/

/* MODULE wkpu1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 */

#include "wkpu1.h"

  /*********************************************
   * Interrupt configurations
   ********************************************/
/*! Interrupt Configuration 0 */
const wkpu_interrupt_cfg_t wkpu1_InterruptCfg0[] =
{
    {
        .hwChannel = 0U,
        .edgeEvent = WKPU_EDGE_NONE,
        .filterEn  = false,
        .pullEn    = false
    },
    {
        .hwChannel = 1U,
        .edgeEvent = WKPU_EDGE_RISING,
        .filterEn  = true,
        .pullEn    = true
    },
    {
        .hwChannel = 2U,
        .edgeEvent = WKPU_EDGE_NONE,
        .filterEn  = false,
        .pullEn    = false
    }
};




/* END wkpu1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
