/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : timing_pal2.c
**     Project     : timing_pal_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : timing_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-30, 20:00, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file timing_pal2.c
** @version 01.00
*/
/*!
**  @addtogroup timing_pal2_module timing_pal2 module documentation
**  @{
*/

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 */

#include <stddef.h>
#include "timing_pal2.h"

/*! @brief PAL instance information */
const timing_instance_t timing_pal2_instance = { TIMING_INST_TYPE_STM, 0U };

/*! @brief Channel configuration array */
timer_chan_config_t timing_pal2_channelConfigs[1] =
{
    /* Channel configuration 0 */
    {
         .channel        = 0U,
         .chanType       = TIMER_CHAN_TYPE_CONTINUOUS,
         .callback       = timing_pal2_channel_callBack0,
         .callbackParam  = NULL
    }
};
/*! @brief IP specific extension configuration */
extension_stm_for_timer_t timing_pal2_stmExtension =
{
    .clockSelect       = STM_CLOCK_SYSTEM,
    .prescaler         = 1U
};
/*! @brief Timer configuration */
timer_config_t timing_pal2_InitConfig =
{
    .chanConfigArray     = timing_pal2_channelConfigs,
    .numChan             = 1U,
    .extension           = &timing_pal2_stmExtension
};

/* END timing_pal2. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
